services:
  - type: web
    name: procureflow-frontend
    env: docker
    plan: free
    branch: development
    dockerContext: .
    dockerfilePath: Dockerfile
    numInstances: 1
    healthCheckPath: /
